// Vendor addresses mapped by merchant name
// These are realistic addresses for the mock slot merchants

const VENDOR_ADDRESSES: Record<string, string> = {
  // UK
  "Luxe Hair Studio": "245 5th Avenue, Manhattan, NY 10016",
  "Harley Street Clinic": "10 Harley Street, London W1G 9PF",
  "Sketch Restaurant": "9 Conduit Street, Mayfair, London W1S 2XG",
  "Third Space Gym": "13 Sherwood Street, Soho, London W1F 7BR",
  "King Street Barbers": "42 King Street, Manchester M2 6BA",
  "Hawksmoor Manchester": "184 Deansgate, Manchester M3 3WB",
  "The Edgbaston Clinic": "22 Hagley Road, Birmingham B16 8PE",
  "Pure Gym Jewellery Qtr": "120 Vyse Street, Birmingham B18 6LP",
  "Timberyard Restaurant": "10 Lady Lawson Street, Edinburgh EH3 9DS",
  "Edinburgh Dermatology": "14 Charlotte Square, Edinburgh EH2 4DR",
  "NetJets UK": "Manchester Airport, Terminal 3, M90 1QX",
  "Ox Restaurant": "1 Oxford Street, Belfast BT1 3LA",
  "Cowshed Spa": "48 Whiteladies Road, Bristol BS8 2NH",
  "David Lloyd Leeds": "Tongue Lane, Leeds LS6 4QW",
  "The Ivy Glasgow": "71 Buchanan Street, Glasgow G1 3HL",
  "Spire Hospital": "Croescadarn Road, Cardiff CF23 8XL",
  "Raby Hunt": "Summerhouse, Darlington DL2 3UD",
  "Rudding Park Spa": "Rudding Lane, Harrogate HG3 1JH",
  "Nuffield Health": "Lenton Lane, Nottingham NG7 2SA",
  "The Orangery Bath": "11-12 The Circus, Bath BA1 2ET",
  "VistaJet UK": "London Heathrow, Terminal 5, TW6 2GA",
  "Port of Felixstowe": "Dock Road, Felixstowe IP11 3SY",
  "F45 Liverpool": "15 Castle Street, Liverpool L2 4SX",
  "Moor Hall": "Prescot Road, Aughton, Lancashire L39 6RT",
  "Skin Clinic Cambridge": "8 Rose Crescent, Cambridge CB2 3LL",
  "Bupa Dental Oxford": "36 Cornmarket Street, Oxford OX1 3HA",
  "Kumon Kensington": "45 Kensington High Street, London W8 5ED",
  "BSM Driving School": "100 Oxford Road, Manchester M1 5WH",
  "West End Shows": "Shaftesbury Avenue, London WC2H 8DP",
  "Kwik Fit MOT": "62 Broad Street, Birmingham B1 2HG",
  "Halfords Autocentre": "Kirkstall Road, Leeds LS4 2DG",
  "Slater & Gordon": "58 Mosley Street, Manchester M2 3HZ",
  "Irwin Mitchell": "40 Holborn Viaduct, London EC1N 2PZ",
  "Foxtons Viewings": "77 Kings Road, London SW3 4NX",
  "Savills Valuations": "33 Castle Street, Edinburgh EH2 3DN",
  "Battersea Vets": "108 Battersea Park Road, London SW11 4ND",
  "Pets at Home Groom": "Unit 5, Cribbs Causeway, Bristol BS10 7TL",
  "Toni & Guy Chelsea": "337 Kings Road, Chelsea, London SW3 5ES",
  "Gordon Ramsay Royal Hospital": "68 Royal Hospital Road, London SW3 4HP",
  "The Corinthia Spa": "Whitehall Place, London SW1A 2BD",
  "Gymbox Bank": "52 Threadneedle Street, London EC2R 8AY",
  "The Shard View": "32 London Bridge Street, London SE1 9SG",
  "AA Driving School": "22 Park Row, Leeds LS1 5JF",
  "Arnold Clark Service": "200 Bothwell Street, Glasgow G2 7EZ",
  "DLA Piper": "1 City Square, Leeds LS1 2ES",
  "Knight Frank": "55 Baker Street, London W1U 8AN",
  "Vets4Pets Edinburgh": "15 Dalry Road, Edinburgh EH11 2BQ",
  "Port of Tilbury": "Dock Road, Tilbury, Essex RM18 7EH",
  "Jet2 Charter": "Leeds Bradford Airport, Leeds LS19 7TU",
  "Bupa Cromwell Hospital": "164 Cromwell Road, London SW5 0TU",
  "Tattu Manchester": "3 Hardman Square, Manchester M3 3EB",
  "Pho Oxford": "78 Westgate, Oxford OX1 1PH",
  "Rush Hair Nottingham": "6 Bridlesmith Gate, Nottingham NG1 2GQ",
  "Clifford Chance": "10 Upper Bank Street, London E14 5JJ",
  "Strutt & Parker": "24 The Promenade, Cheltenham GL50 1NW",
  "Edinburgh Fringe Late": "The Pleasance, 60 The Pleasance, Edinburgh EH8 9TJ",
  "Green Flag Breakdown": "85 Division Street, Sheffield S1 4GE",
  "Explore Learning": "14 Baldwin Street, Bristol BS1 1SE",
  "PDSA Vet Clinic": "Penarth Road, Cardiff CF11 8TQ",

  // North America
  "Atlantic Charter": "100 Fred Wehran Drive, Teterboro, NJ 07608",
  "Dr. Sarah Chen": "9400 Brighton Way, Beverly Hills, CA 90210",
  "SoulCycle Tribeca": "103 Warren Street, New York, NY 10007",
  "Drybar Chicago": "30 N Michigan Avenue, Chicago, IL 60602",
  "Wheels Up": "8960 W Imperial Hwy, Los Angeles, CA 90009",
  "Mayo Clinic Express": "200 First Street SW, Rochester, MN 55905",
  "Canlis Restaurant": "2576 Aurora Avenue N, Seattle, WA 98109",
  "Barry's Miami": "1676 Alton Road, Miami Beach, FL 33139",
  "Port of Vancouver": "100 The Pointe, Vancouver, BC V6C 3T4",
  "Ossington Dental": "55 Ossington Avenue, Toronto, ON M6J 2Y9",
  "Princeton Tutors": "251 W 42nd Street, New York, NY 10036",
  "Broadway Tickets": "1515 Broadway, New York, NY 10036",
  "LegalZoom Consult": "101 N Brand Blvd, Glendale, CA 91203",
  "Compass Realty": "717 Market Street, San Francisco, CA 94103",
  "Banfield Pet Hospital": "2345 N Clark Street, Chicago, IL 60614",
  "Nobu Malibu": "22706 Pacific Coast Hwy, Malibu, CA 90265",
  "Equinox Hudson Yards": "35 Hudson Yards, New York, NY 10001",
  "Tesla Service Center": "12600 N Lamar Blvd, Austin, TX 78753",
  "Perkins Coie LLP": "1201 Third Avenue, Suite 4900, Seattle, WA 98101",
  "Sotheby's Open House": "1334 York Avenue, New York, NY 10021",
  "VCA Animal Hospital": "9599 Jefferson Blvd, Culver City, CA 90232",
  "Kaplan Test Prep": "1 Mifflin Place, Cambridge, MA 02138",
  "Madison Square Events": "4 Pennsylvania Plaza, New York, NY 10001",
  "Port of Los Angeles": "425 S Palos Verdes Street, San Pedro, CA 90731",
  "Cedars-Sinai Urgent": "8700 Beverly Blvd, Los Angeles, CA 90048",
  "Dry Bar Dallas": "8411 Preston Road, Dallas, TX 75225",
  "NetJets USA": "10400 W Higgins Road, Chicago, IL 60018",
  "Alinea Restaurant": "1723 N Halsted Street, Chicago, IL 60614",
  "Orangetheory Denver": "1600 Wynkoop Street, Denver, CO 80202",

  // Europe
  "Le Marais Coiffure": "15 Rue des Archives, 75004 Paris, France",
  "Restaurant L'Ambroisie": "9 Place des Vosges, 75004 Paris, France",
  "Soho House Berlin": "Torstraße 1, 10119 Berlin, Germany",
  "KaDeWe Personal Shopping": "Tauentzienstraße 21-24, 10789 Berlin, Germany",
  "Terme di Saturnia": "Via della Follonata, 58014 Saturnia GR, Italy",
  "Rossella Jardini Atelier": "Via Montenapoleone 8, 20121 Milano, Italy",
  "Glow & Go London": "134 King's Road, London SW3 4XB",
  "Birmingham Fit Studio": "55 Corporation Street, Birmingham B4 6SX",
  "Berlin CrossFit Box": "Kastanienallee 77, 10435 Berlin, Germany",

  // Asia Pacific
  "Mandarin Oriental Spa HK": "5 Connaught Road, Central, Hong Kong",
  "Sushi Saito": "1-4-5 Motoazabu, Minato-ku, Tokyo 106-0046",
  "Gaggan Bangkok": "68/1 Soi Langsuan, Bangkok 10330, Thailand",
  "Virgin Active Singapore": "1 Kim Seng Promenade, Singapore 237994",
  "Air Charter Tokyo": "3-3-2 Hanedakuko, Ota-ku, Tokyo 144-0041",
  "Wentworth Golf": "Wentworth Drive, Virginia Water GU25 4LS",

  // Middle East
  "Emirates Palace Spa": "West Corniche Road, Abu Dhabi, UAE",
  "Zuma Dubai": "DIFC, Gate Village 06, Dubai, UAE",
  "Jetex Dubai": "Dubai South, Al Maktoum Int'l Airport, Dubai, UAE",
  "Etihad Charter": "Khalifa City, Abu Dhabi, UAE",

  // Latin America
  "D.O.M. Restaurant": "Rua Barão de Capanema, 549, São Paulo 01411-011, Brazil",
  "Four Seasons Spa CDMX": "Paseo de la Reforma 500, Mexico City 06600, Mexico",
  "Central Restaurant": "Av. Pedro de Osma 301, Barranco, Lima 04, Peru",

  // Africa
  "The Test Kitchen": "375 Albert Road, Woodstock, Cape Town 7915, South Africa",
  "Serena Spa Nairobi": "Kenyatta Avenue, Nairobi 00100, Kenya",
  "Royal Air Maroc Charter": "Boulevard Mohammed V, Casablanca 20000, Morocco",
};

export const getVendorAddress = (merchantName: string): string | null => {
  return VENDOR_ADDRESSES[merchantName] || null;
};

export const getGoogleMapsUrl = (address: string): string => {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;
};
